- name: demo on variables 
  hosts: all 
 
  vars_files:
      - dev-vars.yml 
  vars:       
      URL: play.google.com 
  tasks: 
    - name: pritning URL  
      ansible.builtin.debug:
        msg: Url that we print is {{ URL }}  
