
    - name: pritning URL with quotes  
      ansible.builtin.debug:
        msg: "{{ URL }}" 
      vars:                 
        URL: task.google.com 
    
    - name: URL for this env is 
      ansible.builtin.debug:
        msg: "{{ ENV }}" 
