- name: demo on outputs 
  hosts: all 
  tasks:
    - name: Running a shell command  
      ansible.builtin.shell: uptime 
      register: OUT
    
    - name: printing out variable 
      ansible.builtin.debug:  
        msg: "{{OUT.stdout}}"
  
  


    - name: printing the uptime status 
      ansible.builtin.debug: 
        msg: status of uptime is {{OUT.rc}}