
- name: demo on conditions 
  hosts: all  
  vars:
    # epic: true 
    # actor: true 
  tasks: 
    - name: Run this when the OS is CentOS 
      ansible.builtin.debug: 
          msg: Hello to centos  
      when: ansible_distribution == "CentOS"

    - name: Run this when the OS is Ubuntu 
      ansible.builtin.debug: 
          msg: Hello to ubuntu  
      when: ansible_distribution == "Ubuntu"




    - name: Run this when actor variable is declared 
      ansible.builtin.debug: 
          msg: Actor is declared  
      when: actor is defined